### ISSUE TITLE
$auth0->getUser() only returns sub and email_confirmed

### ISSUE THREAD

**Issue by tobias74** [auth0-samples/auth0-php-web-app#17]
Maybe I am missing something here, but calling 

$auth0->getUser() 

does not return the userData. In order to get the Userdata, one has to use 

$idToken = $auth0->getIdToken() 

and then issue a call to

$userData = $auth0Api->users->get($idToken);

Then $userData will contain all the user-data.

**Comment by rnicholls** [comment]
I think you are looking for the management API. That will give you access to all of the users info.

**Comment by joshcanhelp** [comment]
`$auth0->getUser()` will give you back whatever user information you asked for with the `scope` parameter used when the object was created. More information [here](https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims) on scopes.
