### ISSUE TITLE
Undefined Function Session_id()

### ISSUE THREAD

**Issue by rnicholls** [auth0-samples/auth0-php-web-app#18]
I have dropped this project on to my server and only changed the proper account keys and I get this error right from the go. 

Fatal error: Uncaught Error: Call to undefined function Auth0\SDK\Store\session_id() in /app/vendor/auth0/auth0-php/src/Store/SessionStore.php:40 Stack trace: #0 /app/vendor/auth0/auth0-php/src/Store/SessionStore.php(30): Auth0\SDK\Store\SessionStore->initSession() #1 /app/vendor/auth0/auth0-php/src/Auth0.php(230): Auth0\SDK\Store\SessionStore->__construct() #2 /app/index.php(18): Auth0\SDK\Auth0->__construct(Array) #3 {main} thrown in /app/vendor/auth0/auth0-php/src/Store/SessionStore.php on line 40

**Comment by alexisluque** [comment]
Hi @rnicholls.What version of PHP

**Comment by rnicholls** [comment]
I am using php 7.0

**Comment by alexisluque** [comment]
@rnicholls try run `php -m | grep session`, and in case of empty output you should install session extension.

**Comment by rnicholls** [comment]
@alexisluque that seems to have been the issue. Looks like I had session installed but not inside my docker image. 

Thank you
