### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by petermeissner** [auth0-samples/auth0-php-web-app#22]
In auth0-php-web-app/tree/master/00-Starter-Seed/README.md there is a typo:

> Box, Salesforce, **amont** others, or enterprise identity systems like Windows Azure AD, Google Apps, Active Directory, ADFS or any SAML

... should be
> Box, Salesforce, **among** others, or enterprise identity systems like Windows Azure AD, Google Apps, Active Directory, ADFS or any SAML

**Comment by aaguiarz** [comment]
Thanks @petermeissner !
