### ISSUE TITLE
Inaccurate instructions in sample app

### ISSUE THREAD

**Issue by siolfyr** [auth0-samples/auth0-php-web-app#24]
If you go here:

https://auth0.com/docs/quickstart/webapp/php?download=true

You'll get instructions to:

> Set the Callback URL in the Application Settings to:
> http://localhost:3000/callback

But then if you do that and click Sign In on the sample app via localhost:3000, it brings you to an oops page, which claims http://localhost:3000 isn't in the list of acceptable callback URLs.

I tried switching the callback URL to http://localhost:3000 and it worked. Should the docs be updated to be more accurate?

**Comment by joshcanhelp** [comment]
@siolfyr - Thank you for this! It looks like we missed one of the automatically updating tags there. Fixing in [auth0/docs#7506](https://github.com/auth0/docs/pull/7506)
