### ISSUE TITLE
SSO does not work

### ISSUE THREAD

**Issue by irriss** [auth0-samples/auth0-php-web-app#42]
I am using Auth0 with SSO and it works fine for my SPAs. Recently I needed to add PHP application to have common SSO with other apps so I used sample app from this repository and it works well,

however if I authenticate in PHP app, my other apps pick up that login silently via SSO, but it does not work in another direction (if I login in my other apps, PHP still see this user as not logged in).

I believe this is because PHP demo app does not check remote session.

Could you please advise how I can add SSO login for PHP demo app?

**Comment by irriss** [comment]
I tried to solve the issue myself and it works. Hoever I am not entierly sure it is done in the best way. Please have a look at PR
https://github.com/auth0-samples/auth0-php-web-app/pull/43

**Comment by evansims** [comment]
Thanks for submitting an issue. Going to be keeping this issue open to investigate.

**Comment by evansims** [comment]
Hey @irriss 👋 Thanks for your question! Unfortunately this topic is a bit outside the scope of this QS; it's just for demonstrating a basic, straightforward webapp. For help with implementing something more elaborate like you're describing, I'd encourage you to raise this question with the support engineers at the [Auth0 Community](https://community.auth0.com/). Thanks!
