### ISSUE TITLE
How to verify after getting redirected to a page from a magic link?

### ISSUE THREAD

**Issue by jobaercfc** [auth0-samples/auth0-php-web-app#44]
I implemented the passwordless authentication and it is sending me a magic link in the email. I need to know how will I verify that I got redirected here from the magic link? If I want I can directly access the page through URL. I want to give a security check and make it protected.

**Comment by evansims** [comment]
Hi @jobaercfc 👋 Sorry for the delay. You could use an approach like setting a custom state during the login() call that your app recognizes on return, or set a cookie or store a value in the session that you can read when the user returns to your app after auth0. For further info on best approaches on that, create a thread on the [Auth0 Community](https://community.auth0.com/).
