### ISSUE TITLE
Invalid state when running login.php using cypress

### ISSUE THREAD

**Issue by bhaumik-rspl** [auth0-samples/auth0-php-web-app#49]
I have cloned this repository and made configuration related changes. I'm able to do login/logout when running application using normal browser.

However, when I write test script for login using cypress its not working anymore. cypress script gets redirected to auth0 domain for login and I write email/password using cypress, up to this point everything is good.

As soon as login is successful and user gets redirected back to application from auth0 it shows me "Invalid state" error.

![cypress](https://user-images.githubusercontent.com/67324595/98243407-e9e9cf80-1f93-11eb-883f-a801f5d7d98b.JPG)

cypress script code

```javascript
it("check for login", function () {
    cy.visit("http://localhost:3000/login.php");
    cy.get('input[name="email"]').type("test@gmail.com");
    cy.get('input[name="password"]').type("test");
    cy.get(".auth0-lock-submit").click();
});
```

**Comment by evansims** [comment]
Hi @bhaumik-rspl 👋  I've not had experience with Cypress personally, but it looks straightforward enough. Considering everything works in your browser as it should, it's probably just a minor configuration issue with your tests. [It might help to reference our CodeceptJS test.](https://github.com/auth0-samples/spa-quickstarts-tests/blob/master/lock_login_test.js)

Is there more to your Cypress configuration that this? Again, I'm not familiar with that test suite, but I tried running the code as you provided and Cypress errors requiring configuration files. It seems like there's a fair bit of folder structure and setup required, if I'm reading the docs right. But I might be invoking your code incorrectly. If there is more to it could you share it in a repo somewhere so I could help you debug this, minus any private configuration data? Or let me know how you're invoking that script so I can help you troubleshoot this further. Thanks!

**Comment by evansims** [comment]
Hey again @bhaumik-rspl 👋  I was able to get Cypress up and running. I was able to replicate your test failing in Cypress, but I am uncertain why exactly. I'm not familiar enough with the tool to explain what the hangup could be. However, functionally, everything in the quickstart app appears to be functioning correctly.

I wrote a new test that should work for you based on our existing test suite:

```
it("check for login", function () {
  cy.visit("http://localhost:3000/");
  cy.get("#qsLoginBtn").click();

  cy.get('input[name="email"]').type("test@gmail.com");
  cy.get('input[name="password"]').type("test");
  cy.get(".auth0-lock-widget-container .auth0-lock-submit").click();

  cy.location("pathname").should("eq", "/");
  cy.get("#qsLogoutBtn").should("exist");

  cy.get("#qsLogoutBtn").click();

  cy.get("#qsLoginBtn").should("exist");
});```

This one worked for me in Cypress, let me know if you have better luck with that.

**Comment by bhaumik-rspl** [comment]
Hey @evansims, Thank you for responding quickly!

I have tried your code but I'm unable to load auth0 login page.

![image](https://user-images.githubusercontent.com/67324595/98334757-9aee7980-2029-11eb-8d80-da57e7e47564.png)

I have also tried setting `chromeWebSecurity: false` parameter in cypress.json file as suggested in cypress error, but then also it didn't solve the problem, script is still not able to redirect to auth0 login screen.

I have directly tried with `/login.php` path and I got redirected to auth0 login page but after that getting same "Invalid state" error. Used your script, just changed path to login.php

![image](https://user-images.githubusercontent.com/67324595/98335229-9a0a1780-202a-11eb-8e6f-970066fc1209.png)

If we talk about Invalid state error, after digging into documents it sounds something related to cookies and its possible that testing script robot handles cookies differently which causes that error.

**Comment by evansims** [comment]
That was my thinking as well, some sort of issue with the way cookie handling works in Cypress. I'm just not familiar enough with Cypress to say for sure really. Sorry about that! It might be worth dropping by Cypress' community and seeing if they could shed any light on it for you

**Comment by bhaumik-rspl** [comment]
I can ask Cypress for help but for that I need to understand the flow of "State management". how and which cookies/local-storage are saved and checked on background to make sure state is valid. so please give me some brief about states.

**Comment by evansims** [comment]
Hey @bhaumik-rspl, hope you had a good weekend 👋  That info is available over on our docs site, https://auth0.com/docs/sessions-and-cookies/authentication-api-cookies. Hope that helps!

**Comment by evansims** [comment]
This might also be relevant/helpful in your search https://auth0.com/docs/libraries/auth0-php/troubleshoot-auth0-php-library

**Comment by thianparallel** [comment]
@bhaumik-rspl Did you find any solution to this? I have similar behavior. My app works well on a regular browser but within cypress test, it fails with an "Invalid state" error.
