### ISSUE TITLE
Log in from facebook doesn´t work in the PHP Web App

### ISSUE THREAD

**Issue by camimonse** [auth0-samples/auth0-php-web-app#5]
Context:

 - We are testing the Lock from the PHP Web App, which is found here: https://auth0.com/docs/quickstart/webapp/php
 - We want to log in with facebook in the **sample project** (the seed project), and **in our own project** (following the steps in the tutorial)

Expected result:

 - That we are asked for our credentials before login in 

Real result:

- The Lock is not asking for the credentials and It logs in right away 

Problem:

 - Authentication is failing (just with facebook).

*this refers to the Auth0 ticket number 3369

**Comment by joshcanhelp** [comment]
Lock is no longer a part of this project. Feel free to comment if this is still an issue.
