### ISSUE TITLE
How to get info from google or github after successful login?

### ISSUE THREAD

**Issue by Bunlong** [auth0-samples/auth0-php-web-app#74]
Hi @evansims

How can I get Google or Github info ( name, email, access_token, refresh_token, expired_access_token, ... etc. ) after successful login?

Thanks!

**Comment by evansims** [comment]
Hi @Bunlong 👋 All of that information is available from the `Auth0::getCredentials()` method. It returns an object with properties that include all the information about the authenticated user, including profile data and tokens.
