### ISSUE TITLE
Latest version requires >= PHP 8.1. `quickstart` container uses 'php:8.0...'

### ISSUE THREAD

**Issue by adamstraube** [auth0-samples/auth0-php-web-app#79]
Just tried running the latest version of this sample and got the following error in browser:

`Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.28. in /app/vendor/composer/platform_check.php on line 24` 

Bumping the `quickstart` image to `php:8.1-cli-alpine` fixed it for me locally

**Comment by evansims** [comment]
Thanks for the heads-up! I've bumped [docker-compose.yml](https://github.com/auth0-samples/auth0-php-web-app/blob/main/app/docker-compose.yml) to 8.1 to resolve the error.
