### ISSUE TITLE
INVALID STATE(COMPOSER/PHP) 

### ISSUE THREAD

**Issue by bhavith0999** [auth0-samples/auth0-php-web-app#80]
I have been implementing log-in logout with quickstart **php** and now I am getting this error. PHP Fatal error: Uncaught Auth0\SDK\Exception\StateException: Invalid state in C:\webpages\phptest\vendor\auth0\auth0-

$auth0 = new \Auth0\SDK\Auth0([
‘domain’ => ‘[domain.eu.auth0.com](http://domain.eu.auth0.com/)’,
‘clientId’ =>‘cientid’,
‘clientSecret’ => ‘clientsecret’,
‘cookieSecret’ =>‘cookie secret’,
‘redirectUri’ =>‘http://localhost/phptest/login.php’

]);

if ($auth0->getExchangeParameters()) {
// If they’re present, we should perform the code exchange.
$auth0->exchange();
}
$session = $auth0->getCredentials();
if ($session === null) {
// User is not logged in!
// Redirect to the Universal Login Page for authentication.
header("Location: " . $auth0->login());
exit;
echo $session;
}
function () use($auth0) {
// Clear the user’s local session with our app, then redirect them to the Auth0 logout endpoint to clear their Auth0 session.
header("Location: " . $auth0->logout(‘http://localhost/phptest/login.php’));
echo ‘logged out’;
exit;
};
echo json_encode($auth0,JSON_PRETTY_PRINT);
echo json_encode($session,JSON_PRETTY_PRINT);

**Comment by evansims** [comment]
Hi, @bhavith0999 👋 Thanks for your question.

For general questions and advice, please [reach out to the Auth0 community](https://community.auth0.com). The support team and other developers are there to help.

An invalid state occurs when the SDK encounters an issue reading anticipated cookies. When `login()` is called, a series of temporary cookies are stored on the client device. After authenticating with Auth0 and being returned to the application, during the `exchange()` call, the SDK checks that those cookies are present and match up with what was expected. An invalid state is thrown when they do not.

There could be any number of things interfering there:
- Browser settings or policies blocking cookies.
- Mixing 127.0.0.1 and localhost (each is considered a uniquely different host, and therefore has separate browser cookie jars.)
- Proxying web server software interfering with cookies (this is often the case with Apache and Nginx; make sure you up their cookie header limits if you're using those.)
